insert into boxscores 
(name, age, position, date, team, homeAway, opponent, result, started, 
minutes, fgm, fga, fgPer, 2fgm, 2fga, 2fgPer, 3fgm, 3fga, 3fgPer, ftm, fta, 
ftPer, orb, drb, trb, ast, stl, blk, tov, pf, pts, gmsc) 
select name, 
age, 
position, 
STR_TO_DATE(date, '%d-%b-%Y'),
team, 
homeAway, 
opponent, 
result, 
started, 
if(minutes = '', 0, CAST(minutes as signed int)),
if(fgm = '', 0, CAST(fgm as signed int)),
if(fga = '', 0, CAST(fga as signed int)),
if (fgPer ='', NULL, CAST(fgPer as decimal(4,3))),
if(2fgm = '', 0, CAST(2fgm as signed int)),
if(2fga = '', 0, CAST(2fga as signed int)),
if (2fgPer ='', NULL, CAST(2fgPer as decimal(4,3))),
if(3fgm = '', 0, CAST(3fgm as signed int)),
if(3fga = '', 0, CAST(3fga as signed int)),
if (3fgPer = '', NULL, CAST(3fgPer as decimal(4,3))),
if(ftm = '' , 0, CAST(ftm as signed int)),
if(fta = '' , 0, CAST(fta as signed int)),
if (ftPer = '', NULL, CAST(ftPer as decimal(4,3))),
if(orb = '' , 0, CAST(orb as signed int)),
if(drb = '' , 0, CAST(drb as signed int)),
if(trb = '' , 0, CAST(trb as signed int)),
if(ast = '' , 0, CAST(ast as signed int)),
if(stl = '' , 0, CAST(stl as signed int)), 
if(blk = '' , 0, CAST(blk as signed int)),
if(tov = '' , 0, CAST(tov as signed int)),
if(pf = '' , 0, CAST(pf as signed int)),
if(pts = '', 0, CAST(pts as signed int)),
if (gmsc='', NULL, CAST(gmsc as decimal(4,3))) from boxscores2;