FROM mysql:8.0.20
## am I gonna have to add commands to set up users here?
## or is that info gonna be held in the /var/lib/mysql local directory?

# somehow this is the same as mounting inside a docker container
# ADD . /path/inside/docker/container


