apiVersion: v1
kind: Service
metadata:
    name: mysql-service
spec:
    ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
    name: mysql-service
subsets:
    - addresses:
        - ip: 69.165.235.248
      ports:
        - port: 3306
# kind: Service
# apiVersion: v1
# metadata:
#   name: sql-service
# spec:
#   type: NodePort
#   selector: 
#     app: feature
#   ports :
#     - protocol: TCP
#       port: 3306
#       nodePort: 32002
#       targetPort : 3306
# ---
# kind: Endpoints
# apiVersion: v1
# metadata: 
#   name: sql-service
# subsets:
#   - addresses:
#     - ip: 127.0.0.1
#   - ports:
#     - port: 3306

